// theme/vue/demo4/src/view/layout/aside/Aside.vue
<template>
  <div class="aside aside-left d-flex flex-column" id="kt_aside" ref="kt_aside">
    <!--begin::Brand-->
    <KTBrand></KTBrand>
    <!--end::Brand-->
    <!--begin::Nav Wrapper-->
    <div
      class="aside-nav d-flex flex-column align-items-center flex-column-fluid pt-7"
    >
      <!--begin::Nav-->
      <ul class="nav flex-column">
        <!--begin::Item-->
        <li class="nav-item mb-5" v-b-tooltip.hover.right="'Latest Reports'">
          <a
            href="#"
            class="nav-link btn btn-icon btn-clean btn-icon-white btn-lg active"
          >
            <i class="flaticon2-protection icon-lg"></i>
          </a>
        </li>
        <!--end::Item-->
        <!--begin::Item-->
        <li class="nav-item mb-5" v-b-tooltip.hover.right="'Metronic Features'">
          <a
            href="#"
            class="nav-link btn btn-icon btn-icon-white btn-lg"
            data-toggle="tab"
            data-target="#kt_aside_tab_2"
            role="tab"
          >
            <i class="flaticon2-list-3 icon-lg"></i>
          </a>
        </li>
        <!--end::Item-->
        <!--begin::Item-->
        <li class="nav-item mb-5" v-b-tooltip.hover.right="'Latest Reports'">
          <a
            href="#"
            class="nav-link btn btn-icon btn-icon-white btn-lg"
            data-toggle="tab"
            data-target="#kt_aside_tab_3"
            role="tab"
          >
            <i class="flaticon2-calendar-6 icon-lg"></i>
          </a>
        </li>
        <!--end::Item-->
        <!--begin::Item-->
        <li
          class="nav-item mb-5"
          v-b-tooltip.hover.right="'Project Management'"
        >
          <a
            href="#"
            class="nav-link btn btn-icon btn-icon-white btn-lg"
            data-toggle="tab"
            data-target="#kt_aside_tab_4"
            role="tab"
          >
            <i class="flaticon2-hourglass-1 icon-lg"></i>
          </a>
        </li>
        <!--end::Item-->
        <!--begin::Item-->
        <li class="nav-item mb-5" v-b-tooltip.hover.right="'User Management'">
          <a
            href="#"
            class="nav-link btn btn-icon btn-icon-white btn-lg"
            data-toggle="tab"
            data-target="#kt_aside_tab_5"
            role="tab"
          >
            <i class="flaticon2-analytics-2 icon-lg"></i>
          </a>
        </li>
        <!--end::Item-->
        <!--begin::Item-->
        <li
          class="nav-item mb-5"
          v-b-tooltip.hover.right="'Finance &amp; Accounting'"
        >
          <a
            href="#"
            class="nav-link btn btn-icon btn-icon-white btn-lg"
            data-toggle="tab"
            data-target="#kt_aside_tab_6"
            role="tab"
          >
            <i class="flaticon2-medical-records-1 icon-lg"></i>
          </a>
        </li>
        <!--end::Item-->
        <!--begin::Item-->
        <li class="nav-item mb-5" v-b-tooltip.hover.right="'User Management'">
          <a
            href="#"
            class="nav-link btn btn-icon btn-icon-white btn-lg"
            data-toggle="tab"
            data-target="#kt_aside_tab_5"
            role="tab"
          >
            <i class="flaticon2-gear icon-lg"></i>
          </a>
        </li>
        <!--end::Item-->
        <!--begin::Item-->
        <li
          class="nav-item mb-5"
          v-b-tooltip.hover.right="'Finance &amp; Accounting'"
        >
          <a
            href="#"
            class="nav-link btn btn-icon btn-icon-white btn-lg"
            data-toggle="tab"
            data-target="#kt_aside_tab_6"
            role="tab"
          >
            <i class="flaticon2-warning icon-lg"></i>
          </a>
        </li>
        <!--end::Item-->
      </ul>
      <!--end::Nav-->
    </div>
    <!--end::Nav Wrapper-->
    <!--begin::Footer-->
    <div
      class="aside-footer d-flex flex-column align-items-center flex-column-auto py-8"
    >
      <!--begin::Quick Panel-->
      <KTQuickPanel></KTQuickPanel>
      <!--end::Quick Panel-->
    </div>
    <!--end::Footer-->
  </div>
</template>

<style lang="scss">
/* hide default vue-bootstrap tab links */
.hide-tabs > div:not(.tab-content) {
  display: none;
}
</style>

<script>
import KTQuickPanel from "@/view/layout/extras/offcanvas/QuickPanel";
import KTBrand from "@/view/layout/brand/Brand";
import KTLayoutAside from "@/assets/js/layout/base/aside.js";

export default {
  name: "Aside",
  components: {
    KTQuickPanel,
    KTBrand
  },
  mounted() {
    this.$nextTick(() => {
      // Init Aside
      KTLayoutAside.init(this.$refs["kt_aside"]);
    });
  }
};
</script>

// theme/angular/demo3/src/app/pages/_layout/components/aside/aside.component.ts
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { LayoutService } from '../../../../_metronic/core';
import { KTUtil } from '../../../../../assets/js/components/util';
import { THIS_EXPR } from '@angular/compiler/src/output/output_ast';

@Component({
  selector: 'app-aside',
  templateUrl: './aside.component.html',
  styleUrls: ['./aside.component.scss'],
})
export class AsideComponent implements OnInit {
  TABS: string[] = [
    'kt_aside_tab_0',
    'kt_aside_tab_1',
    'kt_aside_tab_2',
    'kt_aside_tab_3',
    'kt_aside_tab_4',
    'kt_aside_tab_5',
    'kt_aside_tab_6'];
  activeTabId;
  disableAsideSelfDisplay: boolean;
  asideMenuStatic: true;
  disableAsideSecondaryDisplay: boolean;
  ulCSSClasses: string;
  asideMenuHTMLAttributes: any = {};
  asideMenuCSSClasses: string;
  asideMenuDropdown;
  brandClasses: string;
  asideMenuScroll = 1;
  asideSelfMinimizeToggle = false;


  constructor(private layout: LayoutService, private cdr: ChangeDetectorRef) { }

  ngOnInit(): void {
    this.activeTabId = this.TABS[1];
    // load view settings
    this.disableAsideSelfDisplay =
      this.layout.getProp('aside.self.display') === false;
    this.asideMenuStatic = this.layout.getProp('aside.menu.static');
    this.ulCSSClasses = this.layout.getProp('aside_menu_nav');
    this.asideMenuCSSClasses = this.layout.getStringCSSClasses('aside_menu');
    this.asideMenuHTMLAttributes = this.layout.getHTMLAttributes('aside_menu');
    this.asideMenuDropdown = this.layout.getProp('aside.menu.dropdown') ? '1' : '0';
    this.brandClasses = this.layout.getProp('brand');
    this.asideSelfMinimizeToggle = this.layout.getProp(
      'aside.self.minimize.toggle'
    );
    this.asideMenuScroll = this.layout.getProp('aside.menu.scroll') ? 1 : 0;
    this.asideMenuCSSClasses = `${this.asideMenuCSSClasses} ${this.asideMenuScroll === 1 ? 'scroll my-4 ps ps--active-y' : ''}`;
    this.disableAsideSecondaryDisplay = this.layout.getProp('aside.secondary.display');

  }

  setTab(id) {
    this.activeTabId = id;
    const asideWorkspace = KTUtil.find(
      document.getElementById('kt_aside'),
      '.aside-secondary .aside-workspace'
    );
    if (asideWorkspace) {
      KTUtil.scrollUpdate(asideWorkspace);
    }
    this.cdr.detectChanges();
  }
}

<div class="aside-primary d-flex flex-column align-items-center flex-row-auto">
  <!--begin::Primary-->
  <div
    class="aside-brand d-flex flex-column align-items-center flex-column-auto py-5 py-lg-12"
    id="kt_brand"
    [ngClass]="brandClasses"
  >
    <!--begin::Logo-->
    <a routerLink="/" class="brand-logo">
      <img
        alt="Logo"
        src="./assets/media/logos/logo-letter-2.png"
        class="max-h-30px"
      />
    </a>
    <!--end::Logo-->
  </div>
  <!--begin::Nav Wrapper-->
  <div
    class="aside-nav d-flex flex-column align-items-center flex-column-fluid py-5 scroll scroll-pull"
  >
    <!--begin::Nav-->
    <!--begin::Nav-->
    <ul class="nav flex-column" role="tablist">
      <!--begin::Item-->
      <li
        class="nav-item mb-3"
        placement="right"
        ngbTooltip="Latest project"
        container="body"
      >
        <a
          class="nav-link btn btn-icon btn-clean btn-lg"
          data-toggle="tab"
          [ngClass]="{ active: activeTabId === TABS[1] }"
          (click)="setTab(TABS[1])"
          data-target="#kt_aside_tab_1"
          role="tab"
        >
          <span
            [inlineSVG]="'./assets/media/svg/icons/General/Search.svg'"
            cacheSVG="true"
            class="svg-icon svg-icon-xl"
          ></span>
        </a>
      </li>
      <!--end::Item-->
      <!--begin::Item-->
      <li
        class="nav-item mb-3"
        placement="right"
        ngbTooltip="Metronic Features"
        container="body"
      >
        <a
          class="nav-link btn btn-icon btn-clean btn-lg"
          [ngClass]="{ active: activeTabId === TABS[2] }"
          (click)="setTab(TABS[2])"
          data-toggle="tab"
          data-target="#kt_aside_tab_2"
          role="tab"
        >
          <span
            [inlineSVG]="'./assets/media/svg/icons/Communication/Group.svg'"
            cacheSVG="true"
            class="svg-icon svg-icon-xl"
          ></span>
        </a>
      </li>
      <!--end::Item-->
      <!--begin::Item-->
      <li
        class="nav-item mb-3"
        placement="right"
        ngbTooltip="Latest Reports"
        ngbTooltipClass="tooltip"
        container="body"
      >
        <a
          class="nav-link btn btn-icon btn-clean btn-lg"
          [ngClass]="{ active: activeTabId === TABS[3] }"
          data-toggle="tab"
          data-target="#kt_aside_tab_3"
          role="tab"
        >
          <span
            [inlineSVG]="'./assets/media/svg/icons/Media/Equalizer.svg'"
            cacheSVG="true"
            class="svg-icon svg-icon-xl"
          ></span>
        </a>
      </li>
      <!--end::Item--
      <!--begin::Item-->
      <li
        class="nav-item mb-3"
        placement="right"
        ngbTooltip="Latest Reports"
        ngbTooltipClass="tooltip"
        container="body"
      >
        <a
          class="nav-link btn btn-icon btn-clean btn-lg"
          [ngClass]="{ active: activeTabId === TABS[4] }"
          data-toggle="tab"
          data-target="#kt_aside_tab_4"
          role="tab"
        >
          <span
            [inlineSVG]="'./assets/media/svg/icons/General/Shield-check.svg'"
            cacheSVG="true"
            class="svg-icon svg-icon-xl"
          ></span>
        </a>
      </li>
      <!--end::Item-->
      <!--begin::Item-->
      <li
        class="nav-item mb-3"
        data-toggle="tooltip"
        data-placement="right"
        data-container="body"
        data-boundary="window"
        title="User Management"
        container="body"
      >
        <a
          class="nav-link btn btn-icon btn-clean btn-lg"
          data-toggle="tab"
          data-target="#kt_aside_tab_5"
          [ngClass]="{ active: activeTabId === TABS[5] }"
          role="tab"
        >
          <span
            [inlineSVG]="'./assets/media/svg/icons/Home/Library.svg'"
            cacheSVG="true"
            class="svg-icon svg-icon-xl"
          ></span>
        </a>
      </li>
      <!--end::Item-->
      <!--begin::Item-->
      <li
        class="nav-item mb-3"
        data-toggle="tooltip"
        data-placement="right"
        data-container="body"
        data-boundary="window"
        title="Finance & Accounting"
        container="body"
      >
        <a
          class="nav-link btn btn-icon btn-clean btn-lg"
          [ngClass]="{ active: activeTabId === TABS[6] }"
          data-toggle="tab"
          data-target="#kt_aside_tab_6"
          role="tab"
        >
          <span
            [inlineSVG]="'./assets/media/svg/icons/Files/File-plus.svg'"
            cacheSVG="true"
            class="svg-icon svg-icon-xl"
          ></span>
        </a>
      </li>
      <!--end::Item-->
    </ul>
    <!--begin::Item-->
    <!--end::Nav-->
  </div>
  <!--end::Nav Wrapper-->
  <!--begin::Footer -->
  <app-topbar
    class="aside-footer d-flex flex-column align-items-center flex-column-auto py-4 py-lg-10"
  ></app-topbar>
  <!--end::Footer-->
  <!--end::Primary-->
</div>
<ng-container *ngIf="disableAsideSecondaryDisplay">
  <!--begin::Secondary-->
  <div class="aside-secondary d-flex flex-row-fluid">
    <!--begin::Workspace-->
    <div class="aside-workspace scroll scroll-push my-2">
      <!--begin::Tab Content-->
      <div class="tab-content">
        <!--begin::Tab Pane-->
        <div
          class="tab-pane p-3 px-lg-7 py-lg-5 fade"
          [ngClass]="{ 'show active': activeTabId === TABS[1] }"
          id="kt_aside_tab_1"
        >
          <app-aside-search></app-aside-search>
        </div>
        <!--end::Tab Pane-->
        <!--begin::Tab Pane-->
        <div
          class="tab-pane fade"
          id="kt_aside_tab_2"
          [ngClass]="{ 'show active': activeTabId === TABS[2] }"
        >
          <ng-container *ngIf="asideMenuStatic">
            <!--begin::STATIC Aside-->
            <app-aside-static
              class="aside-menu-wrapper flex-column-fluid"
              id="kt_aside_menu_wrapper"
            ></app-aside-static>
            <!--end::STATIC Aside-->
          </ng-container>
          <ng-container *ngIf="!asideMenuStatic">
            <!--begin::DYNAMIC Aside-->
            <app-aside-dynamic
              class="aside-menu-wrapper flex-column-fluid"
              id="kt_aside_menu_wrapper"
            ></app-aside-dynamic>
            <!--end::DYNAMIC Aside-->
          </ng-container>
        </div>
        <!--end::Tab Pane-->
      </div>
    </div>
  </div>
</ng-container>
