// vue3_bootstrap5/demo1/src/views/resources/Changelog.vue
<template>
  <!--begin::Card-->
  <div class="card">
    <!--begin::Card Body-->
    <div class="card-body p-10 p-lg-15">
      <!--begin::Accordion-->
      <div
        class="accordion accordion-flush accordion-icon-toggle"
        id="kt_accordion_2"
      >
        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_5"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotone/Navigation/Right-2.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.14 - 4 June, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_5"
            class="fs-6 collapse show ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder mb-1">New:</h3>
            <ul class="py-2">
              <li class="py-2">
                Added vue-i18n plugin and menu translation example. Update
                languge in profile dropdown.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/dashboard"
                  >Preview</a
                >
              </li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_4"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotone/Navigation/Right-2.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.13 - 9 June, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_4"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder mb-1">New:</h3>
            <ul class="py-2">
              <li class="py-2">
                Added private chat page.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/apps/chat/private-chat"
                  >Preview</a
                >
              </li>
              <li class="py-2">
                Added group chat page.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/apps/chat/group-chat"
                  >Preview</a
                >
              </li>
              <li class="py-2">
                Added drawer chat page.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/apps/chat/drawer-chat"
                  >Preview</a
                >
              </li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_3"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotone/Navigation/Right-2.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.12 - 28 May, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_3"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder mb-1">New:</h3>
            <ul class="py-2">
              <li class="py-2">
                Added wizard demo pages.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/crafted/pages/wizards/vertical"
                  >Preview</a
                >
              </li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_2"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotone/Navigation/Right-2.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.11 - 26 May, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_2"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder mb-1">New:</h3>
            <ul class="py-2">
              <li class="py-2">
                Setup theme skeleton doc.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/documentation/setup-theme-skeleton"
                  >Preview</a
                >
              </li>
            </ul>
            <h3 class="fs-6 fw-bolder mb-1">Update:</h3>
            <ul class="py-2">
              <li class="py-2">
                Updated sign-in form buttons.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/sign-in"
                  >Preview</a
                >
              </li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_1"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotone/Navigation/Right-2.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.10 - 21 May, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_1"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <ul class="py-2">
              <li class="py-2">Initial release.</li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->
      </div>
      <!--end::Accordion-->
    </div>
    <!--end::Card Body-->
  </div>
  <!--end::Card-->
</template>

<script lang="ts">
import { defineComponent, onMounted } from "vue";
import { themeName } from "@/core/helpers/documentation";
import { setCurrentPageTitle } from "@/core/helpers/breadcrumb";

export default defineComponent({
  name: "changelog",
  components: {},
  setup() {
    onMounted(() => {
      setCurrentPageTitle("Changelog");
    });

    return {
      themeName
    };
  }
});
</script>

// react17_bootstrap5/docs/src/app/gettings-started/Changelog.tsx
import React from 'react'
import {KTSVG} from '../../_metronic/helpers'

export function Changelog() {
  const {REACT_APP_THEME_NAME, REACT_APP_VERSION} = process.env

  return (
    <>
      <div className='accordion accordion-flush accordion-icon-toggle' id='kt_accordion'>
        <div className='accordion-item mb-5'>
          <div
              className='accordion-header py-3 d-flex'
              data-bs-toggle='collapse'
              data-bs-target='#kt_accordion_body_v1_0_0'
              aria-expanded='true'
          >
            <span className='accordion-icon'>
              <KTSVG
                  path='/media/icons/duotone/Navigation/Right-2.svg'
                  className='svg-icon svg-icon-3'
              />
            </span>
            <h3 className='fs-3 text-gray-800 fw-bolder mb-0 ms-4'>
              {REACT_APP_THEME_NAME} {REACT_APP_VERSION} - August 6, 2021
            </h3>
          </div>
          <div
              id='kt_accordion_body_v1_0_0'
              className='fs-6 my-1 py-0 ps-10 collapse show'
              data-bs-parent='#kt_accordion'
          >
            <div className='accordion-body ps-0 pt-0'>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>New:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    Added demo2 react version. <a href="https://preview.keenthemes.com/metronic/react/demo1/dashboard">Preview</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div className='accordion-item mb-5'>
          <div
            className='accordion-header py-3 d-flex'
            data-bs-toggle='collapse'
            data-bs-target='#kt_accordion_body_v1_0_0'
            aria-expanded='true'
          >
            <span className='accordion-icon'>
              <KTSVG
                path='/media/icons/duotone/Navigation/Right-2.svg'
                className='svg-icon svg-icon-3'
              />
            </span>
            <h3 className='fs-3 text-gray-800 fw-bolder mb-0 ms-4'>
              {REACT_APP_THEME_NAME} v8.0.21 - July 30, 2021
            </h3>
          </div>
          <div
            id='kt_accordion_body_v1_0_0'
            className='fs-6 my-1 py-0 ps-10 collapse show'
            data-bs-parent='#kt_accordion'
          >
            <div className='accordion-body ps-0 pt-0'>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>New:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    Dark mode setup doc. <a href="https://preview.keenthemes.com/metronic8/react/demo1-docs/docs/dark-mode">Preview</a>
                  </li>
                </ul>
              </div>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>Fix:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    <code className='ms-0'>Error page </code> redirect issue. Now we have page
                    refresh after redirect from Error pages.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div className='accordion-item mb-5'>
          <div
            className='accordion-header py-3 d-flex'
            data-bs-toggle='collapse'
            data-bs-target='#kt_accordion_body_v1_0_0'
            aria-expanded='true'
          >
            <span className='accordion-icon'>
              <KTSVG
                path='/media/icons/duotone/Navigation/Right-2.svg'
                className='svg-icon svg-icon-3'
              />
            </span>
            <h3 className='fs-3 text-gray-800 fw-bolder mb-0 ms-4'>
              {REACT_APP_THEME_NAME} v8.0.19 - July 20, 2021
            </h3>
          </div>
          <div
            id='kt_accordion_body_v1_0_0'
            className='fs-6 my-1 py-0 ps-10 collapse show'
            data-bs-parent='#kt_accordion'
          >
            <div className='accordion-body ps-0 pt-0'>
              <ul className='my-0 py-0'>
                <li className='py-2'>Initial release</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
